# Generated by Django 5.1 on 2024-08-12 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_vehicleimage_image'),
        ('vehicles', '0003_alter_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='vehicles.vehicle'),
        ),
    ]
