# Generated by Django 5.1 on 2024-08-12 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_vehicleimage_is_main_and_more'),
        ('vehicles', '0003_alter_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='vehicles/images/'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle'),
        ),
    ]
