# Generated by Django 5.1 on 2024-08-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_remove_vehicleimage_is_main_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
