# Generated by Django 5.1 on 2024-08-13 02:25

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_vehicleimage_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to=media.models.get_file_path),
        ),
    ]
