# Generated by Django 5.1 on 2024-08-07 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_displacement', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_type', models.CharField(choices=[('electric', 'Electric'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('gasoline', 'Gasoline')], max_length=10)),
                ('number_of_doors', models.IntegerField()),
                ('year_of_manufacture', models.IntegerField()),
                ('price_in_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand')),
                ('country_of_manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.country')),
            ],
        ),
    ]
