# Generated by Django 5.1 on 2024-08-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
