# Generated by Django 5.1 on 2024-08-11 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.brand'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='country_of_manufacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufactured_vehicles', to='vehicles.country'),
        ),
    ]
