# Generated by Django 5.1 on 2024-08-12 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine_displacement',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_of_doors',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_manufacture',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
